# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2020-2021 Harald Sitter <sitter@kde.org>

stages:
  - test

default:
  before_script:
    - apt-get -qq update
    - apt-get install -y gnupg2 gettext git subversion
    - gem update --system --quiet
    - gem update bundler
    - bundle install
    - gem install minitest-junit simplecov-cobertura
  artifacts:
    reports:
      junit: report.xml
    paths:
      - report.xml
      - coverage/coverage.xml

variables:
  TESTOPT: '--junit --pride'
  LANG: 'C.UTF-8' # container has no LANG by default which messes with ruby's utf8 support

reuse:
  inherit:
    default: false
    variables: false
  image:
    name: fsfe/reuse:latest
    entrypoint: [""] # image by default has some custom script as entrypoint :S
  script:
    - reuse lint

test:2.6:
  image: ruby:2.6
  script:
    - rake test

test:2.7:
  image: ruby:2.7
  script:
    - rake test

test:3.0:
  image: ruby:3.0
  script:
    - rake test

test:3.1:
  image: ruby:3.1
  script:
    - rake test

test:3.2:
  image: ruby:3.2
  script:
    - rake test
