# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2017-2020 Harald Sitter <sitter@kde.org>

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/HeredocIndentation:
  Enabled: false
