language: ruby
rvm:
- 2.1.0
- 2.2.0
- 2.3.0
env:
  global:
  - secure: A03DrflHssgYH/ekZlQUbp93B2aaFszXiiSQDxv1mm9oabuQuAQn+aGZmp1v1eA8SdSVu2PAeWNAUXFTAkgIbxRFUScsdbMyG2hdDiAie9t581PRdcRgcPWDPAoigj1xTgI9dbBTljlIJXQZ6+DuI3SpajfV8rksxRjqlgE5aec=
  - secure: fcBXclhQt2XL2iXQC6b3WVa6KGiWqboZK6AWFq2u1o53WK3Wz7eeG2OJwYakJvr23h4U2vvsTbMRT8fen6HXnywOHqPm83qQ6YdukoO5ky95s0zNFtVNn8Nj+ulZveb+zb+DlzXwuOUTSaBfgY0bN3XR12lM9b8qLy5UlZNGlNI=
notifications:
  irc: "chat.freenode.net#kubuntu-ci"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnupg2
