#!/bin/bash

LANG=en_US.UTF-8
LANGUAGE=en
LC_ALL=en_US.UTF-8

VERSION=5.1.95
BALOO_VERSION=5.5.95
ORIGIN=trunk  # set to trunk or stable

svn --version > /dev/null || { echo "Install subversion"; exit 1; }

mkdir $VERSION
cd $VERSION

echo "kde/workspace"
# start off with all of kde/workspace
../tarme.rb --origin ${ORIGIN} --version $VERSION kde/workspace
cat release_data > $VERSION-release-data

echo "removing"
#not in this release
rm kwindowsaddons* -rf
sed -i '/kwindowsaddons/d' $VERSION-release-data
rm baloo* -rf
sed -i '/baloo/d' $VERSION-release-data
rm kfilemetadata* -rf
sed -i '/kfilemetadata/d' $VERSION-release-data

echo "baloo"
../tarme.rb --origin ${ORIGIN} --version $BALOO_VERSION baloo
cat release_data > $VERSION-release-data
../tarme.rb --origin ${ORIGIN} --version $BALOO_VERSION kfilemetadata
cat release_data > $VERSION-release-data

#frameworks branch set in projects.kde.org
../tarme.rb --origin ${ORIGIN} --version $VERSION libmm-qt
cat release_data >> $VERSION-release-data

../tarme.rb --origin ${ORIGIN} --version $VERSION libkscreen
cat release_data >> $VERSION-release-data

../tarme.rb --origin ${ORIGIN} --version $VERSION kscreen
cat release_data >> $VERSION-release-data

../tarme.rb --origin ${ORIGIN} --version $VERSION libbluedevil
cat release_data >> $VERSION-release-data

../tarme.rb --origin ${ORIGIN} --version $VERSION bluedevil
cat release_data >> $VERSION-release-data

../tarme.rb --origin ${ORIGIN} --version $VERSION user-manager
cat release_data >> $VERSION-release-data

../tarme.rb --origin ${ORIGIN} --version $VERSION kcm-touchpad
cat release_data >> $VERSION-release-data

../tarme.rb --origin ${ORIGIN} --version $VERSION ksshaskpass
cat release_data >> $VERSION-release-data

#plasma-workspace-wallpapers is in svn, special case it here
rm -rf plasma-workspace-wallpapers-$VERSION
svn export svn+ssh://svn@svn.kde.org/home/kde/branches/plasma/5.1/plasma-workspace-wallpapers/ | tail -n 1 | awk '{print $3}' | sed s,\\.,, > $VERSION-release-data-plasma-workspace-wallpapers
perl -i -pe 'chomp if eof' $VERSION-release-data-plasma-workspace-wallpapers
mv plasma-workspace-wallpapers/ plasma-workspace-wallpapers-$VERSION
tar Jcf plasma-workspace-wallpapers-${VERSION}.tar.xz plasma-workspace-wallpapers-${VERSION}
echo >> $VERSION-release-data
echo -n "plasma-workspace-wallpapers;" >> $VERSION-release-data
echo -n "rev" >> $VERSION-release-data
cat $VERSION-release-data-plasma-workspace-wallpapers >> $VERSION-release-data
echo -n ";" >> $VERSION-release-data
echo -n "plasma-workspace-wallpapers-${VERSION}.tar.xz;" >> $VERSION-release-data
sha256sum plasma-workspace-wallpapers-${VERSION}.tar.xz | awk '{print $1}' >> $VERSION-release-data
rm $VERSION-release-data-plasma-workspace-wallpapers

../create_sources_inc $VERSION > source-plasma-${VERSION}.inc
