#!/bin/bash

LANG=en_US.UTF-8
LANGUAGE=en
LC_ALL=en_US.UTF-8

VERSION=5.1.0
ORIGIN=stable  # set to trunk or stable

svn --version > /dev/null || { echo "Install subversion"; exit 1; }

# start off with all of kde/workspace
./tarme.rb --origin ${ORIGIN} --version $VERSION kde/workspace/
cat release_data > $VERSION-release-data

#not in this release
rm kwindowsaddons* -rf
sed -i '/kwindowsaddons/d' $VERSION-release-data
rm muon* -rf
sed -i '/muon/d' $VERSION-release-data
rm kde-gtk-config* -rf
sed -i '/kde-gtk-config/d' $VERSION-release-data

#baloo has the wrong translations set in projects.kde.org cos it's part of kdelibs too
#so brute force it to kde-workspace translations
#Harald: please do not read past here if you don't want to cry
cp lib/kdel10n.rb lib/kdel10n.rb-orig
sed -i "s,#{@module},kde," lib/kdel10n.rb
sed -i "s,#{@section},workspace," lib/kdel10n.rb
./tarme.rb --origin ${ORIGIN} --version $VERSION baloo
cat release_data >> $VERSION-release-data
mv lib/kdel10n.rb-orig lib/kdel10n.rb

./tarme.rb --origin ${ORIGIN} --version $VERSION kfilemetadata
cat release_data >> $VERSION-release-data

#frameworks branch set in projects.kde.org
./tarme.rb --origin ${ORIGIN} --version $VERSION libkscreen
cat release_data >> $VERSION-release-data

./tarme.rb --origin ${ORIGIN} --version $VERSION libnm-qt
cat release_data >> $VERSION-release-data

./tarme.rb --origin ${ORIGIN} --version $VERSION libmm-qt
cat release_data >> $VERSION-release-data

#plasma-workspace-wallpapers is in svn, special case it here
rm -rf plasma-workspace-wallpapers-$VERSION
svn export svn+ssh://svn@svn.kde.org/home/kde/branches/plasma/5.1/plasma-workspace-wallpapers/ | tail -n 1 | awk '{print $3}' | sed s,\\.,, > $VERSION-release-data-plasma-workspace-wallpapers
perl -i -pe 'chomp if eof' $VERSION-release-data-plasma-workspace-wallpapers
mv plasma-workspace-wallpapers/ plasma-workspace-wallpapers-$VERSION
tar Jcf plasma-workspace-wallpapers-${VERSION}.tar.xz plasma-workspace-wallpapers-${VERSION}
echo >> $VERSION-release-data
echo -n "plasma-workspace-wallpapers;" >> $VERSION-release-data
echo -n "rev" >> $VERSION-release-data
cat $VERSION-release-data-plasma-workspace-wallpapers >> $VERSION-release-data
echo -n ";" >> $VERSION-release-data
echo -n "plasma-workspace-wallpapers-${VERSION}.tar.xz;" >> $VERSION-release-data
sha256sum plasma-workspace-wallpapers-${VERSION}.tar.xz | awk '{print $1}' >> $VERSION-release-data
rm $VERSION-release-data-plasma-workspace-wallpapers

mkdir -p 5.1.0
cp *xz 5.1.0/
cp 5.1.0-release-data 5.1.0
./create_sources_inc $VERSION > source-plasma-${VERSION}.inc
