LANG=en_US.UTF-8
LANGUAGE=en
LC_ALL=en_US.UTF-8

MAJOR_VERSION=5
VERSION=5.9.1
SHORT_VERSION=5.9
OLD_VERSION=5.9.0
ORIGIN=stable  # git branch as set in projects.k.o, set to trunk or stable
FTPSTABLE=stable  # set to unstable or stable
OLD_FTPSTABLE=stable  # set to unstable or stable of previous release
BRANCH=Plasma/5.9 # set to master or Plasma/5.x

RELEASETYPE=Bugfix # for changelog, set to Beta, Feature or Bugfix

INFOCHECKOUT="/home/jr/src/www/www/info"                   # svn+ssh://svn@svn.kde.org/home/kde/trunk/www/sites/www/info/
ANNOUNCECHECKOUT="/home/jr/src/www/www/announcements"      # svn+ssh://svn@svn.kde.org/home/kde/trunk/www/sites/www/announcements/
L10NSCRIPTSCHECKOUT="/home/jr/src/www/l10n-kde4/scripts"   # svn+ssh://svn@svn.kde.org/home/kde/trunk/l10n-kde4/scripts/
WWWCHECKOUT="/home/jr/src/www/www"                         # svn+ssh://svn@svn.kde.org/home/kde/trunk/www/sites/www/
UPLOADSERVER="ftpadmin@depot.kde.org"
#UPLOADSERVER="weegie"

RELEASEDATE="Tuesday, 14 February 2017" # usually  `LC_ALL=C date "+%A, %d %B %Y" --date="next Tue"`
RELEASEDATEISO="2017-02-14" # usually  `LC_ALL=C date "+%Y-%m-%d" --date="next Tue"`

VIDEO_KEY="youtube" # type of video: "youtube", "peertube", "video"
VIDEO_VALUE="lm0sqqVcotA" # The video ID used in URL for "youtube" and "peertube", and "true" for "video"

GPG_KEY=EC94D18F7F05997E
RELEASE_DUDE="Jonathan Riddell"
