#!/usr/bin/env ruby
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2014-2021 Jonathan Riddell <jr@jriddell.org>
# SPDX-FileCopyrightText: 2015 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2020 Carl Schwan <carl@carlschwan.eu>

# Makes the announce page, info page and copies in the changelog and pushes to invent git repo

require 'fileutils'
require 'optparse'

require_relative 'lib/frameworks_info_template'
require_relative 'lib/frameworks_announce_template'
require_relative 'lib/plasma_info_template'
require_relative 'lib/plasma_announce_template'
require_relative 'lib/plasma_version'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-n", "--no-announce", "No Announce") do |v|
    options[:noannounce] = v
  end
end.parse!

plasma_versions = PlasmaVersion.new
version = plasma_versions.version
major_version = plasma_versions.major_version

announcecheckout = plasma_versions.wwwcheckout + '/content/announcements'
infocheckout = plasma_versions.wwwcheckout + '/content/info'

if plasma_versions.product == 'plasma'
  info_template = PlasmaInfoTemplate.new
  info_output = info_template.render
  File.write(format('%s/plasma-%s.md', infocheckout, version), info_output)

  if not options.include?(:noannounce)
      announce_template = PlasmaAnnounceTemplate.new
      announce_output = announce_template.render
      # write announcement unless it's a .0, beta or final where we do it manually
      File.write(format('%s/plasma/%s/%s.md', announcecheckout, major_version, version), announce_output) unless version[-2..-1] == "0" or version[-2..-1] == "90" or version[-2..-1] == "80"
  end

  changelog_file = format('%s-%s/%s-%s.md', plasma_versions.product, plasma_versions.version,
                          plasma_versions.old_version,
                          version)
  FileUtils.cp(changelog_file,
              format('%s/changelogs/plasma/%s/', announcecheckout, major_version))
end

if plasma_versions.product == 'frameworks'
  info_template = FrameworksInfoTemplate.new
  info_output = info_template.render
  File.write(format('%s/kde-frameworks-%s.md', infocheckout, version), info_output)

  changelog_file = format('%s-%s/%s-%s.md', plasma_versions.product, plasma_versions.version,
                          plasma_versions.old_version,
                          version)
  changelog_contents = File.open(changelog_file).read

  if not options.include?(:noannounce)
      announce_template = FrameworksAnnounceTemplate.new
      announce_output = announce_template.render
      announce_output += changelog_contents

      # write announcement unless it's a .0, beta or final where we do it manually
      File.write(format('%s/frameworks/%s/%s.md', announcecheckout, major_version, version), announce_output)
  end
end

if plasma_versions.product == 'plasma'
  # Add files
  system('git', 'add', "content/info/plasma-#{version}.md", chdir: plasma_versions.wwwcheckout)           # info file
  system('git', 'add', "content/announcements/changelogs/plasma/#{major_version}/#{changelog_file}", chdir: plasma_versions.wwwcheckout)      # changelog file
  if not options.include?(:noannounce)
      system('git', 'add', "content/announcements/plasma/#{major_version}/#{version}.md", chdir: plasma_versions.wwwcheckout) unless version[-2..-1] == "0" or version[-2..-1] == "90" or version[-2..-1] == "80"
  end
end

if plasma_versions.product == 'frameworks'
  # git add frameworks files
  system('git', 'add', "content/info/kde-frameworks-#{version}.md", chdir: plasma_versions.wwwcheckout)           # info file
  if not options.include?(:noannounce)
      system('git', 'add', "content/announcements/frameworks/#{major_version}/#{version}.md", chdir: plasma_versions.wwwcheckout)
  end
end

# Commit files
system('git', 'commit', '-m', "feat: Add webpage for #{plasma_versions.product.capitalize} #{version}", chdir: plasma_versions.wwwcheckout)

# And push files :)
system('git', 'push', chdir: plasma_versions.wwwcheckout)

# Todo work out where invent puts these previews now
puts 'Find the URL from the CI job and add:'
if plasma_versions.product == 'plasma'
  puts "announcements/plasma/#{major_version}/#{version}/index.html"
  puts "info/plasma-#{version}/index.html"
  puts "announcements/changelogs/plasma/#{major_version}/#{plasma_versions.old_version}-#{version}/index.html"
end
if plasma_versions.product == 'frameworks'
  puts "announcements/frameworks/#{major_version}/#{version}/index.html"
  puts "info/kde-frameworks-#{version}/index.html"
end

system(plasma_versions.browser, "https://invent.kde.org/websites/kde-org/-/pipelines")
