#!/usr/bin/env ruby
#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2015-2016,2024 Jonathan Riddell <jr@jriddell.org>

require 'net/http'
require 'json'
require 'optparse'
require 'fileutils'
require_relative 'lib/plasma_version'

class MakeBranch
  def initialize
    @plasma_versions = PlasmaVersion.new
  end

  def branch
    Dir.chdir("#{@plasma_versions.product}-#{@plasma_versions.version}") do
      FileUtils.copy("#{@plasma_versions.version}-release-data", "release_data")
      branch_name = @plasma_versions.product.capitalize
      system("../../branchme.rb --name #{branch_name}/#{@plasma_versions.branch_version}")
    end
  end
end

makeBranch = MakeBranch.new
makeBranch.branch
