#!/usr/bin/env ruby
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2024 Jonathan Riddell <jr@jriddell.org>

require 'net/http'
require 'json'
require 'optparse'
require 'fileutils'
require_relative 'lib/plasma_version'
require_relative 'lib/kde_identify'
require_relative 'retry'



class MakeChangelog

  def initialize
    @readableNames = {
      "attica": "Attica",
      "foo": "bar"
    }
    @plasma_versions = PlasmaVersion.new
    # override old version for a feature release so we still include changes from last feature not from last beta
    #@plasma_versions.version = "5.3.2"
    @file = "#{@plasma_versions.old_version}-#{@plasma_versions.version}.md"
    @tmpdir = 'tmp-changelog'
    @repos = "git-repositories-for-release-#{@plasma_versions.product}"
    @branch = @plasma_versions.branch
    @version = @plasma_versions.version
    @product = @plasma_versions.product.capitalize
  end

  def cloneRepos
    FileUtils.rm_f(@file)
    FileUtils.rm_rf(@tmpdir)
    FileUtils.mkdir(@tmpdir)
    File.readlines(@repos, chomp: true).each do |repo|
      Dir.chdir(@tmpdir) do
        puts(repo)
        invent_path = KDEIndentify.get_kde_category(repo)
        puts invent_path
        `git clone --reference /home/jr/src/*/#{repo}/kdegit/#{repo} invent:#{invent_path}/#{repo}`
        Dir.chdir(repo) do
          `git checkout #{@branch}`
        end
      end
    end
  end

  def makeTheChangelog
    FileUtils.cp('templates/changelog.md', @file)
    sed('VERSION', @version)
    sed('PRODUCT', @product)
    File.open(@file, 'a') { |f| f.puts(`./create_log.py`) }
    @readableNames.keys.each do |product|
      sed("title=\"#{product.to_s}\"", "title=\"#{@readableNames[product]}\"")
    end
  end

  def sed(text_to_replace, text_to_put_in_place)
    text = File.read(@file)
    File.open(@file, 'w+') {|f| f << text.gsub(text_to_replace, text_to_put_in_place)}
  end

end

makeChangelog = MakeChangelog.new
makeChangelog.cloneRepos
makeChangelog.makeTheChangelog

=begin


echo running create_log
./create_log.py >> ${FILE}

sed 's,="baloo",="Baloo",' ${FILE} -i
sed 's,="bluedevil",="Bluedevil",' ${FILE} -i
sed 's,="breeze",="Breeze",' ${FILE} -i
sed 's,="Breeze-gtk",="Breeze GTK",' ${FILE} -i
sed 's,="Breeze-plymouth",="Breeze Plymouth",' ${FILE} -i
sed 's,="discover",="Discover",' ${FILE} -i
sed 's,="drkonqi",="Dr Konqi",' ${FILE} -i
sed 's,="kdecoration",="KDE Window Decoration Library",' ${FILE} -i
sed 's,="kde-gtk-config",="KDE GTK Config",' ${FILE} -i
sed 's,="kdeplasma-addons",="Plasma Addons",' ${FILE} -i
sed 's,="kgamma5",="Gamma Monitor Calibration Tool",' ${FILE} -i
sed 's,="khelpcenter,="KHelpCenter",' ${FILE} -i
sed 's,="khotkeys",="KDE Hotkeys",' ${FILE} -i
sed 's,="kinfocenter",="Info Center",' ${FILE} -i
sed 's,="kio-extras",="KIO Extras",' ${FILE} -i
sed 's,="kmenuedit",="KMenuEdit",' ${FILE} -i
sed 's,="kscreen",="KScreen",' ${FILE} -i
sed 's,="ksshaskpass",="KSSHAskPass",' ${FILE} -i
sed 's,="ksysguard",="KSysGuard",' ${FILE} -i
sed 's,="kwayland",="KWayland",' ${FILE} -i
sed 's,="kwin",="KWin",' ${FILE} -i
sed 's,="libKScreen",="LibKScreen",' ${FILE} -i
sed 's,="milou",="Milou",' ${FILE} -i
sed 's,="muon",="Muon",' ${FILE} -i
sed 's,="oxygen-fonts",="Oxygen Fonts",' ${FILE} -i
sed 's,="oxygen",="Oxygen",' ${FILE} -i
sed 's,="plasma-browser-integration",="Plasma Browser Integration",' ${FILE} -i
sed 's,="plasma-desktop",="Plasma Desktop",' ${FILE} -i
sed 's,="plasma-firewall",="Plasma Firewall",' ${FILE} -i
sed 's,="plasma-mediacenter",="Plasma Media Center",' ${FILE} -i
sed 's,="plasma-nano",="Plasma Nano",' ${FILE} -i
sed 's,="plasma-nm",="Plasma Networkmanager (plasma-nm)",' ${FILE} -i
sed 's,="plasma-pa",="Plasma Audio Volume Control",' ${FILE} -i
sed 's,="plasma-phone-components",="Plasma Phone Components",' ${FILE} -i
sed 's,="plasma-sdk",="Plasma SDK",' ${FILE} -i
sed 's,="plasma-systemmonitor",="Plasma Systemmonitor",' ${FILE} -i
sed 's,="plasma-workspace",="Plasma Workspace",' ${FILE} -i
sed 's,="Plasma Workspace-wallpapers",="Plasma Workspace Wallpapers",' ${FILE} -i
sed 's,="plymouth-kcm",="Plymouth KControl Module",' ${FILE} -i
sed 's,="powerdevil",="Powerdevil",' ${FILE} -i
sed 's,="sddm-kcm",="SDDM KCM",' ${FILE} -i
sed 's,="systemsettings",="System Settings",' ${FILE} -i
sed 's,="user-manager",="User Manager",' ${FILE} -i
sed 's,="plasma-disks",="Plasma Disks",' ${FILE} -i
sed 's,="plasma-bigscreen",="Plasma Bigscreen",' ${FILE} -i
sed 's,="aura-browser",="Aura Browser",' ${FILE} -i
sed 's,="plank-player",="Plank Player",' ${FILE} -i
sed 's,="plasma-remotecontrollers",="Plasma Remotecontrollers",' ${FILE} -i
sed 's,="flatpak-kcm",="Flatpak Permissions",' ${FILE} -i

echo now edit manually  emacs ${FILE}
=end
