#!/bin/bash

# Use this script to update 1 tar
# ./plasma-update-1-tar plasma-workspace

set -xe

TAR=$1

. VERSIONS.inc

svn --version > /dev/null || { echo "Install subversion"; exit 1; }
pkgdiff --version > /dev/null || { echo "Install pkgdiff"; exit 1; }

cd $VERSION

rm -fr ${TAR}-${VERSION}/
../../tarme.rb --origin ${ORIGIN} --version $VERSION ${TAR}
RELEASE_DATA=`cat release_data`
sed "s,${TAR};.*,$RELEASE_DATA," ${VERSION}-release-data -i

../create_sources_inc $VERSION > source-plasma-${VERSION}.inc
cd ..

echo == diff to previous tar
cd tmp-tests
scp ftpadmin@racnoss.kde.org:${FTPSTABLE}/plasma/${VERSION}/${TAR}-5*xz old.tar.xz
pkgdiff old.tar.xz ../${VERSION}/${TAR}-${VERSION}.tar.xz || true
firefox pkgdiff_reports/old/X_to_${VERSION}/changes_report.html
cd ..
echo == end diff to previous tar

echo now run ./plasma-upload
