#!/bin/bash

set -xe

. VERSIONS.inc

#sudo apt install w3m

ssh $UPLOADSERVER "chmod 755 ${FTPSTABLE}/plasma/${VERSION}"

# remove non-release notice in www/announcements/plasma-5.x.y.php and www/info/plasma-5.x.y.php

sed -i "s/draft: true/draft: false/" ${ANNOUNCECHECKOUT}/plasma/5/${VERSION}.md
sed -i "s/draft: true/draft: false/" ${INFOCHECKOUT}/plasma-${VERSION}.md

# www/announcements/index.php

ANNOUNCEINDEX="<\!-- Plasma ${VERSION} -->\n<strong>${RELEASEDATE}<\/strong> - <a href=\"plasma-${VERSION}\">Plasma ${VERSION}<\/a>\n<br \/>\n\"<em>KDE Ships Plasma ${VERSION}.<\/em>\"\n<p \/>"

# www/index.php
# Updating www/index.php got ported to Ruby
#./plasma-release-webpages

# commit to git
cd ${WWWCHECKOUT}
git diff
git commit -a -m "release plasma ${VERSION}"
git push
cd -

# copy announce over to Dot for publishing


$BROWSER https://kde.org/info/plasma-${VERSION}
$BROWSER https://kde.org/announcements/plasma-${VERSION}
$BROWSER https://kde.org/announcements/
$BROWSER https://kde.org/
$BROWSER https://binary-factory.kde.org/view/Websites/job/Website_kde-org/

rm -rf tmp-announcements
mkdir tmp-announcements

#./plasma-dot-story -v ${VERSION} > tmp-announcements/DOT-STORY.html
#kate tmp-announcements/DOT-STORY.html

#w3m tmp-announcements/DOT-STORY.html  -dump > tmp-announcements/KDE-ANNOUNCE_TEXT.txt
#sed -i "s,Live Images.*,https://kde.org/announcements/plasma-${VERSION}.php\nhttps://kde.org/announcements/plasma-${OLD_VERSION}-${VERSION}-changelog," tmp-announcements/KDE-ANNOUNCE_TEXT.txt
#echo "e-mail me to kde-announce@kde.org" > tmp-announcements/KDE-ANNOUNCE_TEXT2.txt
#cat tmp-announcements/KDE-ANNOUNCE_TEXT.txt >> tmp-announcements/KDE-ANNOUNCE_TEXT2.txt
#kate tmp-announcements/KDE-ANNOUNCE_TEXT2.txt

# post on twitter, g+, facebook, reddit (r/kde and r/linux)
echo "@kdecommunity releases Plasma ${VERSION} to fix your bugs https://kde.org/announcements/plasma/5/${VERSION}" > tmp-announcements/twitter.text
kate tmp-announcements/twitter.text
$BROWSER https://tweetdeck.twitter.com
$BROWSER https://facebook.com/kde
$BROWSER https://mastodon.technology/
$BROWSER https://www.reddit.com/r/kde/submit
$BROWSER https://dot.kde.org/#overlay=node/add/story

# e-mail release-team@kde.org, plasma-devel@kde.org with the happy news
echo "e-mail me to kde-announce@kde.org, release-team@kde.org, plasma-devel@kde.org" > tmp-announcements/release-team
echo "Plasma ${VERSION} is now released https://kde.org/announcements/plasma/5/${VERSION}" >> tmp-announcements/release-team
kate tmp-announcements/release-team
