#!/bin/bash

# Use this script to update 1 tar
# ./plasma-make-1-tar plasma-workspace

TAR=$1

. VERSIONS.inc

svn --version > /dev/null || { echo "Install subversion"; exit 1; }

mkdir $VERSION
cd $VERSION

../../tarme.rb --origin ${ORIGIN} --version $VERSION ${TAR}
sed s,${TAR}.*,`cat release_data`, ${VERSION}-release-data -i

../create_sources_inc $VERSION > source-plasma-${VERSION}.inc

echo == diff to previous tar
cd tests-tmp
scp ftpadmin@depot.kde.org:${FTPSTABLE}/plasma/${VERSION}/${TAR}-5*xz old.tar.xz
tar xf old.tar.xz
diff -urN ${TAR}-${VERSION}/ ../${VERSION/${TAR}-${VERSION}
cd ..
echo == end diff to previous tar

echo now run ./plasma-upload
