#!/usr/bin/env ruby

require 'test/unit'
require_relative 'lib/plasma-tag-test'

class PlasmaTagTestTest < Test::Unit::TestCase
  def setup
    @tagTest = PlasmaTagTest.new
  end

  # def teardown
  # end

  def test_version
    assert_equal @tagTest.version, '5.11.1', 'Version not set.'
  end

  def test_git_repos
    @tagTest.get_git_repos
    assert_equal ['bluedevil', 'breeze', 'breeze-grub'], @tagTest.repos[0..2]
    assert_equal 'xdg-desktop-portal-kde', @tagTest.repos[-1]
    assert_equal nil, @tagTest.repos.find_index('discover')
    assert_equal 5, @tagTest.repos.find_index('plasma-discover')
  end
end
