#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2014-2021 Jonathan Riddell <jr@jriddell.org>
# SPDX-FileCopyrightText: 2015 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2020 Bhushan Shah <bhush94@gmail.com>

# Quick script to update version numbers in Plasma 5 modules
# does a clone, replaces PROJECT_VERSION in CMakeLists.txt and pushes

set -xe

. VERSIONS.inc

# override old version for a feature release so we still include changes from last feature not from last beta
# OLD_VERSION=5.3.2

FILE=${OLD_VERSION}-${VERSION}.md

rm -rf ${FILE}
rm -rf tmp-changelog
mkdir tmp-changelog
WORKSPACE=`cat git-repositories-for-release`
cd tmp-changelog
for project in $WORKSPACE; do
 echo ${project};
 git clone --reference "/home/jr/src/kde/${project}/kdegit/${project}" invent:plasma/${project};
 cd ${project}; git checkout ${BRANCH}; cd ..;
 cd ${project};
 pwd;
 cd ..;
done
cd ..

cat templates/plasma-changelog.md > ${FILE}
sed -i s,VERSION,${VERSION}, ${FILE}

echo running create_log
./create_log.py >> ${FILE}

sed 's,="baloo",="Baloo",' ${FILE} -i
sed 's,="bluedevil",="Bluedevil",' ${FILE} -i
sed 's,="breeze",="Breeze",' ${FILE} -i
sed 's,="Breeze-gtk",="Breeze GTK",' ${FILE} -i
sed 's,="Breeze-plymouth",="Breeze Plymouth",' ${FILE} -i
sed 's,="discover",="Discover",' ${FILE} -i
sed 's,="drkonqi",="Dr Konqi",' ${FILE} -i
sed 's,="kdecoration",="KDE Window Decoration Library",' ${FILE} -i
sed 's,="kde-gtk-config",="KDE GTK Config",' ${FILE} -i
sed 's,="kdeplasma-addons",="Plasma Addons",' ${FILE} -i
sed 's,="kgamma5",="Gamma Monitor Calibration Tool",' ${FILE} -i
sed 's,="khelpcenter,="KHelpCenter",' ${FILE} -i
sed 's,="khotkeys",="KDE Hotkeys",' ${FILE} -i
sed 's,="kinfocenter",="Info Center",' ${FILE} -i
sed 's,="kio-extras",="KIO Extras",' ${FILE} -i
sed 's,="kmenuedit",="KMenuEdit",' ${FILE} -i
sed 's,="kscreen",="KScreen",' ${FILE} -i
sed 's,="ksshaskpass",="KSSHAskPass",' ${FILE} -i
sed 's,="ksysguard",="KSysGuard",' ${FILE} -i
sed 's,="kwayland",="KWayland",' ${FILE} -i
sed 's,="kwin",="KWin",' ${FILE} -i
sed 's,="libKScreen",="LibKScreen",' ${FILE} -i
sed 's,="milou",="Milou",' ${FILE} -i
sed 's,="muon",="Muon",' ${FILE} -i
sed 's,="oxygen-fonts",="Oxygen Fonts",' ${FILE} -i
sed 's,="oxygen",="Oxygen",' ${FILE} -i
sed 's,="plasma-browser-integration",="Plasma Browser Integration",' ${FILE} -i
sed 's,="plasma-desktop",="Plasma Desktop",' ${FILE} -i
sed 's,="plasma-firewall",="Plasma Firewall",' ${FILE} -i
sed 's,="plasma-mediacenter",="Plasma Media Center",' ${FILE} -i
sed 's,="plasma-nano",="Plasma Nano",' ${FILE} -i
sed 's,="plasma-nm",="Plasma Networkmanager (plasma-nm)",' ${FILE} -i
sed 's,="plasma-pa",="Plasma Audio Volume Control",' ${FILE} -i
sed 's,="plasma-phone-components",="Plasma Phone Components",' ${FILE} -i
sed 's,="plasma-sdk",="Plasma SDK",' ${FILE} -i
sed 's,="plasma-systemmonitor",="Plasma Systemmonitor",' ${FILE} -i
sed 's,="plasma-workspace",="Plasma Workspace",' ${FILE} -i
sed 's,="Plasma Workspace-wallpapers",="Plasma Workspace Wallpapers",' ${FILE} -i
sed 's,="plymouth-kcm",="Plymouth KControl Module",' ${FILE} -i
sed 's,="powerdevil",="Powerdevil",' ${FILE} -i
sed 's,="sddm-kcm",="SDDM KCM",' ${FILE} -i
sed 's,="systemsettings",="System Settings",' ${FILE} -i
sed 's,="user-manager",="User Manager",' ${FILE} -i

echo now edit manually  emacs ${FILE}
