#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2015-2020 Jonathan Riddell <jr@jriddell.org>

set -xe

. VERSIONS.inc

rm -f asdf asdf.asc
echo asdf > asdf
gpg --clearsign asdf
rm -f asdf asdf.asc

cd ${VERSION}
cp ${VERSION}-release-data release_data

../../tagme.rb --version ${VERSION}
