#!/bin/bash

set -xe

. VERSIONS.inc

svn --version > /dev/null || { echo "Install subversion"; exit 1; }

mkdir -p $VERSION
cd $VERSION

#echo asdf > asdf
#gpg --clearsign asdf
#rm -f asdf asdf.asc

WORKSPACE=`cat ../git-repositories-for-release`
echo "making tars for $WORKSPACE"
for project in $WORKSPACE; do
  echo ${project}
  if [ $project = "plasma-mediacenter" ]; then
    ../../tarme.rb --origin ${ORIGIN} --version $VERSION --from-config plasma-mediacenter
  else
    ../../tarme.rb --origin ${ORIGIN} --version $VERSION ${project}
  fi
  cat release_data >> $VERSION-release-data
done

echo "running create_sources_inc"
../create_sources_inc $VERSION > source-plasma-${VERSION}.inc
echo "ran create_sources_inc"
