#!/usr/bin/env ruby
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2014-2021 Jonathan Riddell <jr@jriddell.org>
# SPDX-FileCopyrightText: 2015 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2020 Carl Schwan <carl@carlschwan.eu>

require 'fileutils'
require 'optparse'

require_relative 'lib/plasma_info_template'
require_relative 'lib/plasma_announce_template'
require_relative 'lib/plasma_version'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-n", "--no-announce", "No Announce") do |v|
    options[:noannounce] = v
  end
end.parse!

plasma_versions = PlasmaVersion.new
version = plasma_versions.version
major_version = plasma_versions.major_version

info_template = PlasmaInfoTemplate.new
info_output = info_template.render
File.write(format('%s/plasma-%s.md', plasma_versions.infocheckout, version), info_output)

if not options.include?(:noannounce)
    announce_template = PlasmaAnnounceTemplate.new
    announce_output = announce_template.render
    # write announcement unless it's a .0, beta or final where we do it manually
    File.write(format('%s/plasma/%s/%s.md', plasma_versions.announcecheckout, major_version, version), announce_output) unless version[-2..-1] == "0" or version[-2..-1] == "90" or version[-2..-1] == "80"
end

changelog_file = format('%s-%s.md',
                        plasma_versions.old_version,
                        version)
FileUtils.cp(changelog_file,
             format('%s/changelogs/plasma/%s/%s', plasma_versions.announcecheckout, major_version, changelog_file))

# Add files
system('git', 'add', "content/info/plasma-#{version}.md", chdir: plasma_versions.wwwcheckout)           # info file
system('git', 'add', "content/announcements/changelogs/plasma/#{major_version}/#{changelog_file}", chdir: plasma_versions.wwwcheckout)      # changelog file
if not options.include?(:noannounce)
    system('git', 'add', "content/announcements/plasma/#{major_version}/#{version}.md", chdir: plasma_versions.wwwcheckout) unless version[-2..-1] == "0" or version[-2..-1] == "90" or version[-2..-1] == "80"
end

# Commit files
system('git', 'commit', '-m', "feat: Add webpage for Plasma #{version}", chdir: plasma_versions.wwwcheckout)

# And push files :)
system('git', 'push', chdir: plasma_versions.wwwcheckout)
system(plasma_versions.browser, "https://kde.org/announcements/plasma/#{major_version}/#{version}/")
system(plasma_versions.browser, "https://kde.org/info/plasma-#{version}/")
system(plasma_versions.browser, "https://kde.org/announcements/changelogs/plasma/#{major_version}/#{changelog_file}/")
system(plasma_versions.browser, "https://binary-factory.kde.org/view/Websites/job/Website_kde-org/")
puts "Note: Webpages will not appear until draft: true is unset"
