#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2018-2021 Jonathan Riddell <jr@jriddell.org>

# Download tars and changelog generated on the CI machine

set -xe

. VERSIONS.inc

mkdir -p ${VERSION}
rsync -CvzaP --stats xenon:/var/www/files/plasma/${VERSION}/*xz ${VERSION}/
rsync -CvzaP --stats xenon:/var/www/files/plasma/${VERSION}/source-plasma*inc ${VERSION}/
rsync -CvzaP --stats xenon:/var/www/files/plasma/${VERSION}/${VERSION}-release-data ${VERSION}/

cd $VERSION
for asdf in *xz; do gpg2 --armor --detach-sign -o ${asdf}.sig ${asdf}; done
cd -
