#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2015-2021 Jonathan Riddell <jr@jriddell.org>
# SPDX-FileCopyrightText: 2020 Carl Schwan <carl@carlschwan.eu>

# checkout/update web svn bits for announcement

set -xe

. VERSIONS.inc

cd ${L10NSCRIPTSCHECKOUT}
git pull

cd ${WWWCHECKOUT}
git checkout master
git pull

git checkout work/staging
git pull
git rebase master
git commit -a -m 'merge master'
git push
echo "> work/staging now is up to date with master"
