#!/bin/bash

set -xe

. VERSIONS.inc

sudo apt install w3m

ssh $UPLOADSERVER "chmod 755 ${FTPSTABLE}/plasma/${VERSION}"

# remove non-release notice in www/announcements/plasma-5.x.y.php and www/info/plasma-5.x.y.php

sed -i "/NOT OUT YET/d" ${ANNOUNCECHECKOUT}/plasma-${VERSION}.php
sed -i "/NOT OUT YET/d" ${INFOCHECKOUT}/plasma-${VERSION}.php

# www/announcements/index.php

ANNOUNCEINDEX="<\!-- Plasma ${VERSION} -->\n<strong>${RELEASEDATE}<\/strong> - <a href=\"plasma-${VERSION}.php\">Plasma ${VERSION}<\/a>\n<br \/>\n\"<em>KDE Ships Plasma ${VERSION}.<\/em>\"\n<p \/>"

sed -i "s/\(INSERT NEW ENTRIES.*\)/\1\n${ANNOUNCEINDEX}/" ${ANNOUNCECHECKOUT}/index.php

# www/index.php
# Updating www/index.php got ported to Ruby
./plasma-release-redux

# commit to svn
pushd ${ANNOUNCECHECKOUT}
svn diff
svn commit -m "release plasma ${VERSION}"

cd ${INFOCHECKOUT}
svn diff
svn commit -m "release plasma ${VERSION}"

cd ${WWWCHECKOUT}
svn diff
svn commit -m "release plasma ${VERSION}"

# copy announce over to Dot for publishing

popd

firefox https://www.kde.org/info/plasma-${VERSION}.php
firefox https://www.kde.org/announcements/plasma-${VERSION}.php
firefox https://www.kde.org/announcements/index.php
firefox https://www.kde.org/

rm -rf tmp-announcements
mkdir tmp-announcements

./plasma-dot-story -v ${VERSION} > tmp-announcements/DOT-STORY.html
kate tmp-announcements/DOT-STORY.html

w3m tmp-announcements/DOT-STORY.html  -dump > tmp-announcements/KDE-ANNOUNCE_TEXT.txt
sed -i "s,Live Images.*,https://www.kde.org/announcements/plasma-${VERSION}.php\nhttps://www.kde.org/announcements/plasma-${OLD_VERSION}-${VERSION}-changelog.php," tmp-announcements/KDE-ANNOUNCE_TEXT.txt
echo "e-mail me to kde-announce@kde.org" > tmp-announcements/KDE-ANNOUNCE_TEXT2.txt
cat tmp-announcements/KDE-ANNOUNCE_TEXT.txt >> tmp-announcements/KDE-ANNOUNCE_TEXT2.txt
kate tmp-announcements/KDE-ANNOUNCE_TEXT2.txt

# post on twitter, g+, facebook, reddit (r/kde and r/linux)
echo "@kdecommunity releases Plasma ${VERSION} to fix your bugs https://www.kde.org/announcements/plasma-${VERSION}.php" > tmp-announcements/twitter.text
kate tmp-announcements/twitter.text
firefox http://twitter.com
firefox https://plus.google.com/+KdeOrg
firefox https://www.reddit.com/r/kde/submit
firefox https://dot.kde.org/#overlay=node/add/story

# e-mail release-team@kde.org, plasma-devel@kde.org with the happy news
echo "e-mail me to kde-announce@kde.org, release-team@kde.org, plasma-devel@kde.org" > tmp-announcements/release-team
echo "Plasma ${VERSION} is now released https://www.kde.org/announcements/plasma-${VERSION}.php" >> tmp-announcements/release-team
kate tmp-announcements/release-team
