#!/bin/bash
# upload plasma tars
# Copyright Jonathan Riddell, may be copied under the GNU GPL v2 or later

set -xe

. VERSIONS.inc

#set this for alpha only
#UPLOADSERVER=embra 

echo == making directory
ssh ${UPLOADSERVER} mkdir -p ${FTPSTABLE}/plasma/${VERSION}/
ssh ${UPLOADSERVER} chmod 750 ${FTPSTABLE}/plasma/${VERSION}/
echo == uploading
rsync -CvzaP --stats ${VERSION}/*xz ${VERSION}/*xz.sig ${UPLOADSERVER}:${FTPSTABLE}/plasma/${VERSION}/

echo == uploading release-data file to http://embra.edinburghlinux.co.uk/~jr/tmp/${VERSION}-release-data
scp ${VERSION}/${VERSION}-release-data ${SCRATCH_SERVER}

mkdir -p tmp-tests

echo == start diff tarballs test, check for diff below
ssh ${UPLOADSERVER} ls ${FTPSTABLE}/plasma/${VERSION}/ | sed s,-5.*xz,, > tmp-tests/${VERSION}-tars
ssh ${UPLOADSERVER} ls ${OLD_FTPSTABLE}/plasma/${OLD_VERSION}/ | sed s,-5.*xz,, > tmp-tests/${OLD_VERSION}-tars
diff -u tmp-tests/${OLD_VERSION}-tars tmp-tests/${VERSION}-tars | tee tmp-tests/${VERSION}-tars-testoutput
echo == end diff tarballs test

echo == start tarballs l10n probe test, check for diff below
ssh ${UPLOADSERVER} "for asdf in ${FTPSTABLE}/plasma/${VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /po/ | sed s,.*-${VERSION}/,, | sed s,.*-${BALOO_VERSION}/,, | grep .po$ | sort; done " > tmp-tests/${VERSION}-po
ssh ${UPLOADSERVER} "for asdf in ${OLD_FTPSTABLE}/plasma/${OLD_VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /po/ | sed s,.*-${OLD_VERSION}/,, | sed s,.*-${OLD_BALOO_VERSION}/,, | grep .po$ | sort; done " > tmp-tests/${OLD_VERSION}-po
diff -u tmp-tests/${OLD_VERSION}-po tmp-tests/${VERSION}-po | tee tmp-tests/${VERSION}-po-testoutput
echo == end tarballs l10n probe test

echo == start tarballs docs probe test, check for diff below
ssh ${UPLOADSERVER} "for asdf in ${FTPSTABLE}/plasma/${VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /doc/ | sed s,.*-${VERSION}/,, | sed s,.*-${BALOO_VERSION}/,, | grep -v /$ | sort; done " > tmp-tests/${VERSION}-doc
ssh ${UPLOADSERVER} "for asdf in ${OLD_FTPSTABLE}/plasma/${OLD_VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /doc/ | sed s,.*-${OLD_VERSION}/,, | sed s,.*-${OLD_BALOO_VERSION}/,, | grep -v /$ | sort; done " > tmp-tests/${OLD_VERSION}-doc
diff -u tmp-tests/${OLD_VERSION}-doc tmp-tests/${VERSION}-doc | tee tmp-tests/${VERSION}-doc-testoutput
echo == end tarballs l10n probe test

#echo == pkgdiff to previous tar
#WORKSPACE=`cat git-repositories-for-release`
#echo "making tars for $WORKSPACE"
#cd tmp-tests
#for TAR in $WORKSPACE; do
#  scp ${UPLOADSERVER}:${FTPSTABLE}/plasma/${OLD_VERSION}/${TAR}-${OLD_VERSION}.tar.xz ${TAR}-${OLD_VERSION}.tar.xz
#  pkgdiff ${TAR}-${OLD_VERSION}.tar.xz ../${VERSION}/${TAR}-${VERSION}.tar.xz || true
#  rm ${TAR}-${OLD_VERSION}.tar.xz
#done
#scp -r pkgdiff_reports/ ${SCRATCH_SERVER}
#firefox http://embra.edinburghlinux.co.uk/~jr/tmp/pkgdiff_reports/${TAR}/${OLD_VERSION}_to_${VERSION}/changes_report.html
#cd -
#echo == end pkgdiff to previous tar

echo == start updating info page source-plasma-${VERSION}.html
cp ${VERSION}/source-plasma-${VERSION}.inc ${INFOCHECKOUT}/sources/source-plasma-${VERSION}.html
cd ${INFOCHECKOUT}
git add sources/source-plasma-${VERSION}.html || true
git diff sources/source-plasma-${VERSION}.html
git commit -m "update source-plasma-${VERSION}.inc"; cd -
git push
echo == end updating info page source-plasma-${VERSION}.html

echo → Read and check the test output in tmp-tests/${VERSION}-doc-testoutput tmp-tests/${VERSION}-po-testoutput tmp-tests/${VERSION}-tars-testoutput
