#!/usr/bin/env ruby

#Put USERNAME='foo' PASSWORD='bar' in wordpress_access.rb
require_relative 'kdewordpress'

plasma_versions = PlasmaVersion.new
version = plasma_versions.version

publish(format('/plasma-%s', version), format("Plasma %s", version), (PlasmaAnnounceTemplateWp.new).render)

changelog_file = format('/plasma-%s-%s-changelog', plasma_versions.old_version, version)
publish(changelog_file, format("Plasma %s Change Log", version), (PlasmaInfoTemplateWp.new).render)
