#!/usr/bin/env ruby
# Copyright (C) 2020 Carl Schwan <carl@carlschwan.eu>

require 'fileutils'

require_relative 'lib/plasma_info_template'
require_relative 'lib/plasma_announce_template'
require_relative 'lib/plasma_version'

plasma_versions = PlasmaVersion.new
version = plasma_versions.version

info_template = PlasmaInfoTemplate.new
info_output = info_template.render
File.write(format('%s/plasma-%s.md', plasma_versions.infocheckout, version), info_output)

announce_template = PlasmaAnnounceTemplate.new
announce_output = announce_template.render
# write announcement unless it's a .0, beta or final where we do it manually
File.write(format('%s/plasma-%s.md', plasma_versions.announcecheckout, version), announce_output) unless version[-2..-1] == "0" or version[-2..-1] == "90" or version[-2..-1] == "80"

changelog_file = format('plasma-%s-%s-changelog.md',
                        plasma_versions.old_version,
                        version)
FileUtils.cp(changelog_file,
             format('%s/%s', plasma_versions.announcecheckout, changelog_file))

# Add files
system('git', 'add', "content/info/plasma-#{version}.md", chdir: plasma_versions.wwwcheckout)           # info file 
system('git', 'add', "content/announcements/#{changelog_file}", chdir: plasma_versions.wwwcheckout)      # changelog file
system('git', 'add', "content/announcements/plasma-#{version}.md", chdir: plasma_versions.wwwcheckout) unless version[-2..-1] == "0" or version[-2..-1] == "90" or version[-2..-1] == "80"

# Commit files
system('git', 'commit', '-m', "feat: Add webpage for Plasma #{version}", chdir: plasma_versions.wwwcheckout)

# And push files :)
system('git', 'push', chdir: plasma_versions.wwwcheckout)
system(plasma_versions.browser, "https://kde.org/announcements/plasma-#{version}")
system(plasma_versions.browser, "https://kde.org/info/plasma-#{version}")
system(plasma_versions.browser, "https://kde.org/announcements/#{changelog_file}")
system(plasma_versions.browser, "https://binary-factory.kde.org/view/Websites/job/Website_kde-org/")
