#!/bin/bash

. VERSIONS.inc

svn --version > /dev/null || { echo "Install subversion"; exit 1; }

mkdir $VERSION
cd $VERSION

echo "kde/workspace"
# start off with all of kde/workspace
../../tarme.rb --origin ${ORIGIN} --version $VERSION kde/workspace
cat release_data >> $VERSION-release-data

echo "removing"
#not in this release
rm libbluedevil* -rf
sed -i '/libbluedevil/d' $VERSION-release-data
#needs different version
rm baloo* -rf
sed -i '/baloo/d' $VERSION-release-data
rm kfilemetadata* -rf
sed -i '/kfilemetadata/d' $VERSION-release-data
# TODO consider not including this or PMC in final?
#rm user-manager* -rf
#sed -i '/user-manager/d' $VERSION-release-data

echo "baloo"
../../tarme.rb --origin ${ORIGIN} --version $BALOO_VERSION baloo
cat release_data >> $VERSION-release-data
../../tarme.rb --origin ${ORIGIN} --version $BALOO_VERSION kfilemetadata
cat release_data >> $VERSION-release-data

echo "plasma-sdk"
../../tarme.rb --origin ${ORIGIN} --version $VERSION plasma-sdk
cat release_data >> $VERSION-release-data

##plasma-workspace-wallpapers is in svn, special case it here
#rm -rf plasma-workspace-wallpapers-$VERSION
#svn export svn+ssh://svn@svn.kde.org/home/kde/branches/plasma/${SHORT_VERSION}/plasma-workspace-wallpapers/ | tail -n 1 | awk '{print $3}#' | sed s,\\.,, > $VERSION-release-data-plasma-workspace-wallpapers
#perl -i -pe 'chomp if eof' $VERSION-release-data-plasma-workspace-wallpapers
#mv plasma-workspace-wallpapers/ plasma-workspace-wallpapers-$VERSION
#tar Jcf plasma-workspace-wallpapers-${VERSION}.tar.xz plasma-workspace-wallpapers-${VERSION}
#echo >> $VERSION-release-data
#echo -n "plasma-workspace-wallpapers;" >> $VERSION-release-data
#echo -n "rev" >> $VERSION-release-data
#cat $VERSION-release-data-plasma-workspace-wallpapers >> $VERSION-release-data
#echo -n ";" >> $VERSION-release-data
#echo -n "plasma-workspace-wallpapers-${VERSION}.tar.xz;" >> $VERSION-release-data
#sha256sum plasma-workspace-wallpapers-${VERSION}.tar.xz | awk '{print $1}' >> $VERSION-release-data
#rm $VERSION-release-data-plasma-workspace-wallpapers

sed -i s,5.\d,${SHORT_VERSION}, ../projects/plasma-workspace-wallpapers-stable
../../tarme.rb --origin ${ORIGIN} --version ${VERSION} --from-config plasma-workspace-wallpapers-${ORIGIN}
# releaseme doesn't add release_data for svn currently
#cat release_data >> $VERSION-release-data

../create_sources_inc $VERSION > source-plasma-${VERSION}.inc
