#!/usr/bin/env ruby
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2018 Jonathan Riddell <jr@jriddell.org>

# This script moves some of the plasma-webpages processing into Ruby

require 'fileutils'

require_relative 'lib/plasma_version'
require_relative 'lib/plasma_www_index_template'

wwwindexupdater = WWWIndexUpdater.new
index_html = wwwindexupdater.rewrite_index

File.write(wwwindexupdater.wwwcheckout, index_html)
