#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Jonathan Riddell

# For CI server to run QA tests

set -xe

. VERSIONS.inc

tars=`cat git-repositories-for-release`

mkdir tmp-tests

echo == download old tars ==
mkdir -p old-tars
cd old-tars
for tar in $tars; do echo ${tar}; wget https://download.kde.org/${OLD_FTPSTABLE}/plasma/${OLD_VERSION}/${tar}-${OLD_VERSION}.tar.xz; done
cd -
echo == old tars downloaded ==

echo == start tarballs l10n probe test, check for diff below
for tar in $tars; do tar --list -f old-tars/${tar}-${OLD_VERSION}.tar.xz | awk '{print $6}' | grep /po/ | sed s,.*-${VERSION}/,, | sed s,.*-${BALOO_VERSION}/,, | grep .po$ | sort; done >> ${VERSION}-po-testoutput
echo == start tarballs l10n probe test, check for diff below
cat ${VERSION}-po-testoutput
echo == end tarballs l10n probe test

echo == start po probe test, check for diff below
ssh ${UPLOADSERVER} "for asdf in ${FTPSTABLE}/plasma/${VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /po/ | sed s,.*-${VERSION}/,, | sed s,.*-${BALOO_VERSION}/,, | grep .po$ | sort; done " > tmp-tests/${VERSION}-po
ssh ${UPLOADSERVER} "for asdf in ${OLD_FTPSTABLE}/plasma/${OLD_VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /po/ | sed s,.*-${OLD_VERSION}/,, | sed s,.*-${OLD_BALOO_VERSION}/,, | grep .po$ | sort; done " > tmp-tests/${OLD_VERSION}-po
echo == l10n po files diff:
diff -u tmp-tests/${OLD_VERSION}-po tmp-tests/${VERSION}-po | tee tmp-tests/${VERSION}-po-testoutput
echo == end po probe test

echo == start tarballs docs probe test, check for diff below
ssh ${UPLOADSERVER} "for asdf in ${FTPSTABLE}/plasma/${VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /doc/ | sed s,.*-${VERSION}/,, | sed s,.*-${BALOO_VERSION}/,, | grep -v /$ | sort; done " > tmp-tests/${VERSION}-doc
ssh ${UPLOADSERVER} "for asdf in ${OLD_FTPSTABLE}/plasma/${OLD_VERSION}/*xz; do tar --list -f \${asdf} | awk '{print $6}' | grep /doc/ | sed s,.*-${OLD_VERSION}/,, | sed s,.*-${OLD_BALOO_VERSION}/,, | grep -v /$ | sort; done " > tmp-tests/${OLD_VERSION}-doc
diff -u tmp-tests/${OLD_VERSION}-doc tmp-tests/${VERSION}-doc | tee tmp-tests/${VERSION}-doc-testoutput
echo == end tarballs docs probe test
