#!/usr/bin/env ruby

# This script moves some of the plasma-webpages processing into Ruby

require 'fileutils'

require_relative 'lib/plasma_version'
require_relative 'lib/plasma_www_index_template'

wwwindexupdater = WWWIndexUpdater.new
index_html = wwwindexupdater.rewrite_index

File.write(wwwindexupdater.wwwcheckout, index_html)
