#!/bin/bash

. VERSIONS.inc

svn --version > /dev/null || { echo "Install subversion"; exit 1; }

mkdir $VERSION
cd $VERSION

WORKSPACE=`cat ../git-repositories-for-release`
echo "making tars for $WORKSPACE"
for project in $WORKSPACE; do
  echo ${project}
  ../../tarme.rb --origin ${ORIGIN} --version $VERSION ${project}
  cat release_data >> $VERSION-release-data
done

../create_sources_inc $VERSION > source-plasma-${VERSION}.inc
