#!/usr/bin/env ruby
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2017 Jonathan Riddell <jr@jriddell.org>

require_relative 'lib/plasma-tag-test'

tag_test = PlasmaTagTest.new
tag_test.grab_git_repos
tag_test.check_tags
