#!/bin/bash

# checkout/update web svn bits for announcement

set -xe

. VERSIONS.inc

cd ${INFOCHECKOUT}
svn update

cd ${ANNOUNCECHECKOUT}
svn update

cd ${L10NSCRIPTSCHECKOUT}
svn update

cd ${WWWCHECKOUT}
svn update
